name: page_transformer
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1
  sqflite: ^0.11.1
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/background.jpeg
    - assets/background.jpg
    - assets/veg1.jpg
    - assets/fruit.jpg
    - assets/nonveg.jpg
    - assets/splashbackground.jpg